use anchor_lang::prelude::*;

#[error_code]
pub enum OathError {
    #[msg("Protocol creation is paused")] Paused,
    #[msg("Unauthorized signer")] Unauthorized,
    #[msg("Creator cannot review their own Oath")] SelfApproval,
    #[msg("Duplicate reviewer")] DuplicateReviewer,
    #[msg("Reviewer has already approved this milestone")] AlreadyApproved,
    #[msg("Reviewer is not in the immutable reviewer set")] WrongReviewer,
    #[msg("Threshold must be positive and at most the reviewer count")] InvalidThreshold,
    #[msg("Too many reviewers")] TooManyReviewers,
    #[msg("Invalid reviewer public key")] InvalidReviewer,
    #[msg("Allocation exceeds the committed amount")] AllocationExceedsCommitted,
    #[msg("Allocation must fully cover commitment before activation")] IncompleteAllocation,
    #[msg("Milestone has already been claimed")] AlreadyClaimed,
    #[msg("Milestone has not reached approval threshold")] NotApproved,
    #[msg("Finalize the milestone before claiming")] NotClaimable,
    #[msg("Deadline has not passed")] DeadlineNotPassed,
    #[msg("Deadline has passed")] DeadlinePassed,
    #[msg("Invalid deadline")] InvalidDeadline,
    #[msg("Wrong asset mint")] WrongMint,
    #[msg("Wrong vault")] WrongVault,
    #[msg("Oath is already active or complete")] AlreadyActivated,
    #[msg("Vault does not hold the full commitment")] ActivationFundingFailed,
    #[msg("Economic configuration is immutable after activation")] MutationAfterActivation,
    #[msg("Oath is not active")] NotActive,
    #[msg("Launch configuration is locked")] LaunchLocked,
    #[msg("Maximum three Oaths per launch")] TooManyOaths,
    #[msg("Too many milestones")] TooManyMilestones,
    #[msg("Amount must be positive")] ZeroAmount,
    #[msg("Checked arithmetic failed")] ArithmeticOverflow,
    #[msg("Invalid PDA")] InvalidPda,
    #[msg("Wrong program owner")] WrongOwner,
    #[msg("Invalid milestone state transition")] InvalidMilestoneState,
    #[msg("Milestone is terminal")] TerminalMilestone,
    #[msg("Evidence is missing or already frozen")] InvalidEvidence,
    #[msg("Wrong fixed failure recipient")] WrongRecipient,
    #[msg("Native SOL cannot use the SPL burn action")] UnsupportedSolBurn,
    #[msg("Failure is not ready for execution")] FailureNotReady,
    #[msg("Vault balance is insufficient")] InsufficientVaultBalance,
    #[msg("Every milestone must be supplied in index order")] IncompleteMilestoneList,
    #[msg("Every milestone must be settled before completion")] UnsettledMilestone,
    #[msg("SPL vault has an unexpected delegate or close authority")] UnsafeVault,
    #[msg("Invalid funding asset type")] WrongAssetType,
    #[msg("Protocol initialization requires the program upgrade authority")] InvalidUpgradeAuthority,
    // Appended after the deployed V1 table so existing error codes (6000..6041) never move.
    #[msg("Launches are gated and the creator is not on the allowlist")] LaunchesGated,
    #[msg("Creator allowlist is full")] AllowlistFull,
    #[msg("Creator is already on the allowlist")] AlreadyAllowlisted,
    #[msg("Creator is not on the allowlist")] NotAllowlisted,
    #[msg("Account is not a Meteora DBC virtual pool")] NotDbcPool,
    #[msg("DBC pool creator is not the signer")] PoolCreatorMismatch,
    #[msg("DBC pool base mint is not the launch mint")] PoolMintMismatch,
    #[msg("DBC pool config does not match the supplied config")] PoolConfigMismatch,
    // Appended together during the B2 security-fix merge; order preserves each
    // fix's own error but the exact codes only matter for not colliding with
    // anything already deployed at merge time (nothing below this line has
    // shipped yet).
    #[msg("Only a Draft Oath can be cancelled")] NotDraft,
    #[msg("Oath collateral mint must not have a live freeze authority")] MintHasFreezeAuthority,
    #[msg("Recipient associated token account is missing; create it before settlement")] RecipientAtaMissing,
}
